# Generated by Django 5.0.12 on 2025-02-24 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_post', 'Can post articles.')]},
        ),
    ]
